---
title: "Resolution"
output: 
  rmarkdown::html_vignette:
    fig_width: 6
vignette: >
  %\VignetteIndexEntry{Resolution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sdcSpatial)
```

# Resolution dependency of sensitivity

The sensitivity of a raster map is dependent on the choosen base resolution: 
a detailed map has many cells with a sole observation, and a coarse map has many 
observations, but may hide patterns: e.g. a raster map with one cell has lowest sensitivity, but a flat spatial distribution.

##

```{r}
resolution <- seq(50, 1e3, by=50)
sens <- sapply(resolution, function(r){
  sdc <- sdc_raster(enterprises, "production", r = r)
  sensitivity_score(sdc)
})

plot(resolution, sens, type="b", las=1, ylim=c(0,1))
```


```{r}
sdc <- sdc_raster(enterprises, "production", r = 100) 
plot(sdc)
print(sdc)
bandwidth <- seq(100, 2e3, by=100)
sens <- sapply(bandwidth, function(bw){
  sdc_sm <- protect_smooth(sdc, bw = bw)
  raster::plot(sdc_sm$value$sum)
  sensitivity_score(sdc_sm)
})

plot(bandwidth, sens, type="b", las=1, ylim=c(0,1))
```

